PR Issues #3 & #4
l-lemaitre/blog_php pull request #5
Opened 2022-06-06 08:50 UTC by l-lemaitre

2022-06-07 09:47 UTC, dylanfevrier requested changes
Top ces ajouts ! Beau boulot ! 🔥 

Quelques petits retours afin d'améliorer le code et de séparer les responsabilités. Petit détail, l'ensemble de ton code doit être en anglais. Cela inclut les constantes, les noms de classes CSS mais aussi les variables, fonctions...

2022-06-07 09:47 UTC, dylanfevrier commented on classes/models/DatabaseConnection.php
> +<?php
Globalement pour cette classe, je t'invite à tee renseigner sur le Design Pattern singleton. Celui-ci te permettra de créer qu'une seule connexion à ta DB !

2022-06-07 09:47 UTC, dylanfevrier commented on classes/controllers/FrontController.php
> +            $query = "SELECT * FROM `article` WHERE `id_article` = ?";
Globalement, tu devrais éviter les query et actions sur la DB directement dans le controlleur. Ce n'est pas sa responsabilité. 

Je te conseille d'utiliser un Modèle (une classe dédiée) pour effectuer tes requêtes. 

Concrètement, l'idée c'est de séparer ton code et sa responsabilité. Chaque classe dispose d'une responsabilité qui lui est propre.

2022-06-07 09:47 UTC, dylanfevrier commented on public/css/stylesheet.scss
> +      .titreFil {
Idéalement, ton code devrait être entièrement en anglais !

2022-06-07 09:47 UTC, dylanfevrier commented on classes/controllers/FrontController.php
> +            $resultSet = $bdd->query($query, array("Publié"));
Ton status devrait être "published".

D'ailleurs je t'invite à utiliser des constantes pour ce type de cas afin de standardiser la valeur et d'avoir un seul point de vérité et de modification

2022-06-11 14:11 UTC, l-lemaitre commented
Je pense avoir appliqué les 4 retours dont tu m'as fait part plus haut dans le [commit](https://github.com/l-lemaitre/blog_php/commit/a664bb178aace1094194ff33dbb41523f67d5441)  "2d commit Issues https://github.com/l-lemaitre/blog_php/issues/3 & https://github.com/l-lemaitre/blog_php/issues/4".

2022-06-16 20:05 UTC, dylanfevrier commented on classes/models/Article.php
> +    define("PUBLISHED", "Published");
Ici, tu peux simplement faire dans ta classe article 

```
class Article {
   // ... reste des attributs 

    const PUBLISHED = "Published";

   // .... tes méthodes ici
}
```

Ensuite tu as la possibilité de faire Article::PUBLISHED dans ton code afin de faire référence à ta constante

2022-06-16 20:05 UTC, dylanfevrier commented on classes/models/Article.php
> +
Il faudrait qu'on revoit ensemble cette notion et la diff entre ton repository et ton entity !

2022-06-26 19:59 UTC, merged